app = "jopec305-03-flyioapp"

[[services]]
    internal_port = 3030
    protocol = "tcp"
    min_machines_running = 0

[[services.ports]]
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.tcp_checks]]
    interval = 1000
    timeout = 20000